global using System.Linq.Expressions; 
global using FoodRush.Domain.Entites;
global using System.Net;
global using FoodRush.Application.Common;
global using FoodRush.Application.DTOs;
global using MediatR;
global using FoodRush.Application.Contract.Interface;
global using Microsoft.Extensions.DependencyInjection;
global using System.Reflection;
global using AutoMapper;
global using FoodRush.Application.AutoMapper;
global using FluentValidation;
global using Microsoft.AspNetCore.Http;
global using System.ComponentModel.DataAnnotations;
global using FoodRush.Application.Contract.Service;
global using Microsoft.Extensions.Configuration;
global using System.Security.Cryptography;
global using FoodRush.Domain.Common.Enum;

